### ISSUE TITLE
systemTime Error: Too few results left

### ISSUE THREAD

**Issue by hummelstrand** [nrkno/tv-automation-server-core#6]
Getting the following console errors running commit 2d73397:
```I20180516-10:43:43.420(2)? systemTime Error Error: Too few results left
I20180516-10:43:43.420(2)?     at Promise.then (server/timesync.ts:116:37)
I20180516-10:43:43.420(2)?     at /Users/jonashummelstrand/.meteor/packages/promise/.0.10.2.5g5mso.orhhi++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20180516-10:44:03.424(2)? Updating systemTime...```

**Comment by nytamin** [comment]
During startup, the application connects to ntp-servers and tries to sync the application time to them. This error message comes when it wasn't able to enough good measurements to to be able to sync the time accurately ("accurately" = within 1/60s). This is dependent on current network conditions and latencies.
The exact number of required measurements and number of retries could/should probably be tweaked so that false positives are avoided while still guaranteeing operability.

**Comment by nytamin** [comment]
We should also discuss whether we should throw an error or simply display a warning.

**Comment by nytamin** [comment]
Closing this, I think this was resolved a long time ago
