### ISSUE TITLE
Fresh install of Sofie crash.

### ISSUE THREAD

**Issue by olzzon** [nrkno/tv-automation-server-core#78]
Hi,

I have just installed Sofie on a new machine. 
I have the Playout Gateway and the MOS Gateway running.
But when I try to run Sofie (using "meteor") I get this error.
``` 
client/ui/Prompter/PrompterView.tsx (85, 3): Type '{ mirror: boolean; mirrorv: boolean; restrictMode: string | string[] | undefined; followTake: boo...' is not assignable to type 'PrompterConfig'
```

Have tried both Master and Develop branch.

**Comment by olzzon** [comment]
Here´s the full error:
```
=> Started proxy.                             
client/ui/Prompter/PrompterView.tsx (85, 3): Type '{ mirror: boolean; mirrorv: boolean; restrictMode: string | string[] | undefined; followTake: boo...' is not assignable to type 'PrompterConfig'.
  Types of property 'restrictMode' are incompatible.
    Type 'string | string[] | undefined' is not assignable to type 'string | undefined'.
      Type 'string[]' is not assignable to type 'string | undefined'.
        Type 'string[]' is not assignable to type 'string'.
client/ui/Prompter/PrompterView.tsx (90, 23): Argument of type 'string | string[] | null | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
client/ui/Prompter/PrompterView.tsx (91, 21): Argument of type 'string | string[] | null | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
=> Meteor 1.8.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
W20190408-10:02:38.907(2)? (STDERR) {"date":"Mon Apr 08 2019 10:02:36 GMT+0200 (CEST)","process":{"pid":23822,"uid":1000,"gid":1000,"cwd":"/home/ndi/sofie/tv-automation-server-core/meteor/.meteor/local/build/programs/server","execPath":"/home/ndi/.meteor/packages/meteor-tool/.1.6.1_4.qkg478.l0i3e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node","version":"v8.11.4","argv":["/home/ndi/.meteor/packages/meteor-tool/.1.6.1_4.qkg478.l0i3e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node","/home/ndi/sofie/tv-automation-server-core/meteor/.meteor/local/build/main.js","program.json"],"memoryUsage":{"rss":158351360,"heapTotal":114016256,"heapUsed":82087920,"external":23374768}},"os":{"loadavg":[0.97119140625,0.9287109375,0.89697265625],"uptime":334227},"trace":[{"column":18,"file":"module.js","function":"Module._extensions..node","line":681,"method":".node","native":false},{"column":32,"file":"module.js","function":"Module.load","line":565,"method":"load","native":false},{"column":12,"file":"module.js","function":"tryModuleLoad","line":505,"method":null,"native":false},{"column":3,"file":"module.js","function":"Module._load","line":497,"method":"_load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":596,"method":"require","native":false},{"column":18,"file":"internal/module.js","function":"require","line":11,"method":null,"native":false},{"column":48,"file":"/home/ndi/sofie/tv-automation-server-core/meteor/node_modules/bindings/bindings.js","function":"bindings","line":112,"method":null,"native":false},{"column":32,"file":"/home/ndi/sofie/tv-automation-server-core/meteor/node_modules/node-expat/lib/node-expat.js","function":null,"line":4,"method":null,"native":false},{"column":30,"file":"module.js","function":"Module._compile","line":652,"method":"_compile","native":false},{"column":10,"file":"module.js","function":"Module._extensions..js","line":663,"method":".js","native":false},{"column":32,"file":"module.js","function":"Module.load","line":565,"method":"load","native":false},{"column":12,"file":"module.js","function":"tryModuleLoad","line":505,"method":null,"native":false},{"column":3,"file":"module.js","function":"Module._load","line":497,"method":"_load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":596,"method":"require","native":false},{"column":18,"file":"internal/module.js","function":"require","line":11,"method":null,"native":false},{"column":13,"file":"/home/ndi/sofie/tv-automation-server-core/meteor/node_modules/xml2json/lib/xml2json.js","function":null,"line":1,"method":null,"native":false},{"column":30,"file":"module.js","function":"Module._compile","line":652,"method":"_compile","native":false},{"column":10,"file":"module.js","function":"Module._extensions..js","line":663,"method":".js","native":false},{"column":32,"file":"module.js","function":"Module.load","line":565,"method":"load","native":false},{"column":12,"file":"module.js","function":"tryModuleLoad","line":505,"method":null,"native":false},{"column":3,"file":"module.js","function":"Module._load","line":497,"method":"_load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":596,"method":"require","native":false},{"column":18,"file":"internal/module.js","function":"require","line":11,"method":null,"native":false},{"column":18,"file":"/home/ndi/sofie/tv-automation-server-core/meteor/node_modules/xml2json/lib/index.js","function":null,"line":3,"method":null,"native":false},{"column":30,"file":"module.js","function":"Module._compile","line":652,"method":"_compile","native":false},{"column":10,"file":"module.js","function":"Module._extensions..js","line":663,"method":".js","native":false},{"column":32,"file":"module.js","function":"Module.load","line":565,"method":"load","native":false},{"column":12,"file":"module.js","function":"tryModuleLoad","line":505,"method":null,"native":false}],"stack":["Error: The module '/home/ndi/sofie/tv-automation-server-core/meteor/node_modules/node-expat/build/Release/node_expat.node'","was compiled against a different Node.js version using","NODE_MODULE_VERSION 64. This version of Node.js requires","NODE_MODULE_VERSION 57. Please try re-compiling or re-installing","the module (for instance, using `npm rebuild` or `npm install`).","    at Object.Module._extensions..node (module.js:681:18)","    at Module.load (module.js:565:32)","    at tryModuleLoad (module.js:505:12)","    at Function.Module._load (module.js:497:3)","    at Module.require (module.js:596:17)","    at require (internal/module.js:11:18)","    at bindings (/home/ndi/sofie/tv-automation-server-core/meteor/node_modules/bindings/bindings.js:112:48)","    at Object.<anonymous> (/home/ndi/sofie/tv-automation-server-core/meteor/node_modules/node-expat/lib/node-expat.js:4:32)","    at Module._compile (module.js:652:30)","    at Object.Module._extensions..js (module.js:663:10)","    at Module.load (module.js:565:32)","    at tryModuleLoad (module.js:505:12)","    at Function.Module._load (module.js:497:3)","    at Module.require (module.js:596:17)","    at require (internal/module.js:11:18)","    at Object.<anonymous> (/home/ndi/sofie/tv-automation-server-core/meteor/node_modules/xml2json/lib/xml2json.js:1:13)","    at Module._compile (module.js:652:30)","    at Object.Module._extensions..js (module.js:663:10)","    at Module.load (module.js:565:32)","    at tryModuleLoad (module.js:505:12)","    at Function.Module._load (module.js:497:3)","    at Module.require (module.js:596:17)","    at require (internal/module.js:11:18)","    at Object.<anonymous> (/home/ndi/sofie/tv-automation-server-core/meteor/node_modules/xml2json/lib/index.js:3:18)","    at Module._compile (module.js:652:30)","    at Object.Module._extensions..js (module.js:663:10)","    at Module.load (module.js:565:32)","    at tryModuleLoad (module.js:505:12)"],"level":"error","message":"uncaughtException: The module '/home/ndi/sofie/tv-automation-server-core/meteor/node_modules/node-expat/build/Release/node_expat.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 64. This version of Node.js requires\nNODE_MODULE_VERSION 57. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`)."}
```

**Comment by nytamin** [comment]
Thanks for this bug report. There's probably something wrong with some typings, I'll get back to you shortly.

**Comment by nytamin** [comment]
I've pushed a fix onto /develop, let me know it if fixes your issue :)

**Comment by baltedewit** [comment]
I don't think the typings issue causes the crash. This bit of the log seems particularly interesting:

"stack":["Error: The module '/home/ndi/sofie/tv-automation-server-core/meteor/node_modules/node-expat/build/Release/node_expat.node'","was compiled against a different Node.js version using","NODE_MODULE_VERSION 64. This version of Node.js requires","NODE_MODULE_VERSION 57. Please try re-compiling or re-installing","the module (for instance, using `npm rebuild` or `npm install`)."

It might be that Meteor is using a different node version internally then you are using and if so should be fixed by executing a `meteor npm rebuild`

**Comment by nytamin** [comment]
ah, you're probably right, @baltedewit, I missed the last line in the error message (the one that counted)..

**Comment by nytamin** [comment]
To add to Balte's answer: If `meteor npm rebuild` doesn't help, try downgrading your node-version to version 8 (preferably using [nvm ](https://github.com/creationix/nvm)) when doing the install.

**Comment by olzzon** [comment]
```meteor npm rebuild ```  did the job.
And as always I forgot rule number one: 
```
Read the full error message.
```
Thanks :)

**Comment by olzzon** [comment]
Wrong nodejs version. "meteor nom rebuild" fixed it.

**Comment by olzzon** [comment]
Wrong nodejs version. "meteor nom rebuild" fixed it.
